version: 2
updates:
  - package-ecosystem: "npm" # main website
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
  - package-ecosystem: "npm" # firebase functions
    directory: "/functions"
    schedule:
      interval: "weekly"
    target-branch: "dev"