name: Deploy to Firebase Hosting on merge
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - 'README.md'
      - 'firestore.rules'
      - 'storage.rules'
      - 'firestore.indexes.json'
      - '.env.example'
      - 'functions/**'
      - '.github/**'
      - '.vscode/**'
jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: yarn install

      - name: Run migrations
        env:
          VITE_APP_ENV: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
          FIREBASE_SERVICE_ACCOUNT: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCROLLBARWEB2 }}'
        run: yarn migrate

  build_and_deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
    needs: migrate
    env:
      HTTPS: "true"
      VITE_APP_FIREBASE_API_KEY: '${{ secrets.FIREBASE_API_KEY }}'
      VITE_APP_FIREBASE_AUTH_DOMAIN: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'
      VITE_APP_FIREBASE_PROJECT_ID: '${{ secrets.FIREBASE_PROJECT_ID }}'
      VITE_APP_FIREBASE_STORAGE_BUCKET: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'
      VITE_APP_FIREBASE_MESSAGING_SENDER_ID: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'
      VITE_APP_FIREBASE_APP_ID: '${{ secrets.FIREBASE_APP_ID }}'
      VITE_APP_FIREBASE_MEASUREMENT_ID: '${{ secrets.FIREBASE_MESSUREMENT_ID }}'
      VITE_APP_ENV: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
      ENV: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - run: yarn install && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCROLLBARWEB2 }}
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}

  deploy_functions:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
    needs: build_and_deploy
    env:
      VITE_APP_ENV: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - run: yarn install && yarn build
      - name: Install firebase tools
        run: yarn global add firebase firebase-tools

      - uses: 'google-github-actions/auth@v3'
        with:
          project_id: '${{ secrets.FIREBASE_PROJECT_ID }}'
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCROLLBARWEB2 }}'

      - name: Deploy functions
        run: firebase deploy --only functions